export const handleBFRelation = () => {
  const bfRelations = [
    {
      driveFolder: "THIGH LIFT",
      sizeNameFolder: "500_400",
      path: "thigh-lift",
      images: [
        "Before After 945.png",
        "Before After 944.png",
        "Before After 939.png",
        "Before After 938.png",
        "Before After 937.png",
        "Before After 936.png",
        "Before After 931.png",
        "Before After 929.png",
        "Before After 927.png",
        "Before After 925.png",
        "Before After 910.png",
        "Before After 909.png",
        "Before After 905.png",
        "Before After 903.png",
        "Before After 901.png",
      ],
    },
    {
      driveFolder: "RHINOPLASTY",
      sizeNameFolder: "500_400",
      path: "rhinoplasty-nose-reshaping",
      images: [
        "Копия Before After 190.png",
        "Копия Before After 188.png",
        "Копия Before After 181.png",
        "Before After 371.png",
        "Before After 320.png",
        "Before After 319.png",
        "Before After 318.png",
        "Before After 317.png",
        "Before After 316.png",
        "Before After 315.png",
        "Before After 314.png",
        "Before After 313.png",
        "Before After 312.png",
        "Before After 311.png",
        "Before After 310.png",
        "Before After 308.png",
        "Before After 307.png",
        "Before After 306.png",
        "Before After 305.png",
        "Before After 304.png",
        "Before After 303.png",
        "Before After 302.png",
        "Before After 301.png",
        "Before After 300.png",
        "Before After 299.png",
        "Before After 298.png",
        "Before After 254.png",
        "Before After 253.png",
        "Before After 252.png",
        "Before After 247.png",
        "Before After 246.png",
        "Before After 245.png",
        "Before After 244.png",
        "Before After 243.png",
        "Before After 242.png",
        "Before After 235.png",
        "Before After 234.png",
        "Before After 233.png",
        "Before After 229.png",
        "Before After 227.png",
        "Before After 225.png",
      ],
    },
    {
      driveFolder: "OTOPLASTY",
      sizeNameFolder: "500_400",
      path: "otoplasty",
      images: [
        "Before After 476.png",
        "Before After 474.png",
        "Before After 472.png",
        "Before After 470.png",
        "Before After 468.png",
        "Before After 464.png",
        "Before After 463.png",
        "Before After 461.png",
        "Before After 459.png",
        "Before After 458.png",
        "Before After 451.png",
        "Before After 449.png",
        "Before After 447.png",
      ],
    },
    {
      driveFolder: "MOMMY MAKEOVER",
      sizeNameFolder: "500_400",
      path: "mommy-makeover",
      images: [
        "Before After 778.png",
        "Before After 776.png",
        "Before After 774.png",
        "Before After 772.png",
        "Before After 761.png",
        "Before After 760.png",
        "Before After 759.png",
        "Before After 758.png",
        "Before After 757.png",
        "Before After 751.png",
        "Before After 749.png",
        "Before After 747.png",
        "Before After 744.png",
        "Before After 741.png",
      ],
    },
    {
      driveFolder: "LIPOSUCTION",
      sizeNameFolder: "500_400",
      path: "liposuction",
      images: [
        "Before After 750.png",
        "Before After 748.png",
        "Before After 746.png",
        "Before After 745.png",
        "Before After 743.png",
        "Before After 742.png",
        "Before After 740.png",
        "Before After 739.png",
        "Before After 725.png",
        "Before After 724.png",
        "Before After 723.png",
        "Before After 722.png",
        "Before After 721.png",
        "Before After 720.png",
        "Before After 718.png",
        "Before After 709.png",
        "Before After 708.png",
        "Before After 707.png",
        "Before After 706.png",
        "Before After 701.png",
        "Before After 699.png",
        "Before After 697.png",
        "Before After 695.png",
        "Before After 691.png",
        "Before After 689.png",
        "Before After 687.png",
      ],
    },
    {
      driveFolder: "FACELIFT",
      sizeNameFolder: "500_400",
      path: "face-lift",
      images: [
        "Before After 750.png",
        "Before After 748.png",
        "Before After 746.png",
        "Before After 745.png",
        "Before After 743.png",
        "Before After 742.png",
        "Before After 740.png",
        "Before After 739.png",
        "Before After 725.png",
        "Before After 724.png",
        "Before After 723.png",
        "Before After 722.png",
        "Before After 721.png",
        "Before After 720.png",
        "Before After 718.png",
        "Before After 709.png",
        "Before After 708.png",
        "Before After 707.png",
        "Before After 706.png",
        "Before After 701.png",
        "Before After 699.png",
        "Before After 697.png",
        "Before After 695.png",
        "Before After 691.png",
        "Before After 689.png",
        "Before After 687.png",
      ],
    },
    {
      driveFolder: "DOUBLE CHIN LIPOSUCTION",
      sizeNameFolder: "500_400",
      path: "double-chin-liposuction",
      images: [
        "Before After 577.png",
        "Before After 575.png",
        "Before After 573.png",
        "Before After 571.png",
        "Before After 569.png",
        "Before After 567.png",
        "Before After 565.png",
        "Before After 563.png",
        "Before After 561.png",
        "Before After 559.png",
        "Before After 557.png",
      ],
    },
    {
      driveFolder: "BUTTOCK AUGMENTATION",
      sizeNameFolder: "500_400",
      path: "breast-augmentation-implants",
      images: [
        "Before After 1002.png",
        "Before After 1001.png",
        "Before After 1000.png",
        "Before After 995.png",
        "Before After 994.png",
        "Before After 990.png",
        "Before After 983.png",
        "Before After 982.png",
        "Before After 981.png",
        "Before After 980.png",
        "Before After 975.png",
        "Before After 974.png",
        "Before After 973.png",
        "Before After 969.png",
        "Before After 968.png",
        "Before After 967.png",
        "Before After 966.png",
        "Before After 961.png",
        "Before After 960.png",
        "Before After 959.png",
        "Before After 958.png",
        "Before After 957.png",
        "Before After 956.png",
        "Before After 955.png",
        "Before After 947.png",
        "Before After 946.png",
        "Before After 923.png",
        "Before After 922.png",
        "Before After 921.png",
        "Before After 920.png",
        "Before After 919.png",
        "Before After 918.png",
        "Before After 911.png",
      ],
    },
    {
      driveFolder: "BREAST AUGMENTATION",
      sizeNameFolder: "500_400",
      path: "breast-augmentation-implants",
      images: [
        "Копия Before After 203.png",
        "Копия Before After 202.png",
        "Копия Before After 201.png",
        "Копия Before After 200.png",
        "Копия Before After 198.png",
        "Копия Before After 197.png",
        "Копия Before After 196.png",
        "Копия Before After 195.png",
        "Копия Before After 194.png",
        "Копия Before After 193.png",
        "Копия Before After 192.png",
        "Before After 1081.png",
        "Before After 1079.png",
        "Before After 1077.png",
        "Before After 1076.png",
        "Before After 1075.png",
        "Before After 1074.png",
        "Before After 1069.png",
        "Before After 1068.png",
        "Before After 1065.png",
        "Before After 1064.png",
        "Before After 1063.png",
        "Before After 1062.png",
        "Before After 1061.png",
        "Before After 1055.png",
        "Before After 1054.png",
        "Before After 1053.png",
        "Before After 1052.png",
        "Before After 1047.png",
        "Before After 1046.png",
        "Before After 1043.png",
        "Before After 1042.png",
        "Before After 1041.png",
        "Before After 1040.png",
        "Before After 1035.png",
        "Before After 1034.png",
        "Before After 1033.png",
        "Before After 1032.png",
        "Before After 1026.png",
        "Before After 1023.png",
        "Before After 1022.png",
        "Before After 1019.png",
        "Before After 1018.png",
        "Before After 1017.png",
        "Before After 1016.png",
        "Before After 1015.png",
        "Before After 1014.png",
        "Before After 1013.png",
        "Before After 1012.png",
        "Before After 1003.png",
      ],
    },
    {
      driveFolder: "BRAZILIAN BUTT LIFT",
      sizeNameFolder: "500_400",
      path: "brazilian-butt-lift",
      images: [
        "Before After 829.png",
        "Before After 825.png",
        "Before After 823.png",
        "Before After 816.png",
        "Before After 814.png",
        "Before After 812.png",
        "Before After 810.png",
        "Before After 808.png",
        "Before After 806.png",
        "Before After 804.png",
        "Before After 802.png",
        "Before After 781.png",
        "Before After 780.png",
        "Before After 779.png",
        "Before After 777.png",
        "Before After 775.png",
        "Before After 773.png",
      ],
    },
    {
      driveFolder: "BLEPHAROPLASTY",
      sizeNameFolder: "500_400",
      path: "blepharoplasty-upper-lower",
      images: [
        "Before After 406.png",
        "Before After 401.png",
        "Before After 400.png",
        "Before After 399.png",
        "Before After 398.png",
        "Before After 395.png",
        "Before After 394.png",
        "Before After 392.png",
        "Before After 390.png",
        "Before After 388.png",
        "Before After 386.png",
        "Before After 381.png",
        "Before After 380.png",
        "Before After 377.png",
        "Before After 375.png",
        "Before After 373.png",
        "Before After 368.png",
        "Before After 366.png",
        "Before After 364.png",
        "Before After 362.png",
        "Before After 360.png",
        "Before After 358.png",
      ],
    },
    {
      driveFolder: "ALMOND EYE AESTHETICS",
      sizeNameFolder: "500_400",
      path: "almond-eye",
      images: [
        "Before After 445.png",
        "Before After 437.png",
        "Before After 435.png",
        "Before After 427.png",
        "Before After 426.png",
        "Before After 425.png",
        "Before After 424.png",
        "Before After 423.png",
        "Before After 422.png",
        "Before After 418.png",
        "Before After 417.png",
        "Before After 416.png",
        "Before After 414.png",
        "Before After 412.png",
        "Before After 408.png",
      ],
    },
  ];
  return bfRelations;
};

// 'fue-hair-transplant',
//   'dhi-hair-transplant',
//   'prp-hair-treatment',
//   'mesotherapy-hair',
//   'beard-transplant',
//   'moustache-transplant',
//   'eyebrow-transplant',
//   'rhinoplasty-nose-reshaping',
//   'blepharoplasty-upper-lower',
//   'labiaplasty-in-turkey',
//   'double-chin-liposuction',
//   'otoplasty',
//   'thighplasty-in-turkey',
//   'brow-lift',
//   'neck-lift',
//   'brazilian-butt-lift',
//   'liposuction',
//   'arm-lift',
//   'thigh-lift',
//   'breast-augmentation-implants',
//   'breast-lift-mastopexy',
//   'labiaplasty-barbie-look',
//   'penile-enlargement-phalloplasty',
//   '6-4-dental-implants',
//   'root-canal-therapy',
//   'laminate-veneers',
//   'dental-crowns',
//   'teeth-whitening',
//   'hollywood-smile',
//   'clear-aligners-invisalign',
//   'gum-grafting',
//   'laser-gum-treatments',
//   'bone-grafting',
//   'tummy-tuck-abdominoplasty',
//   'glaucoma-treatment',
//   'diabetic-retinopathy-treatment',
//   'intraocular-lens',
//   'corneal-transplantation',
//   'male-infertility',
//   'male-sexual-health-issues',
//   'peyronies-disease',
//   'erectile-dysfunction-ed',
//   'stem-cell-for-men',
//   'orthopedic-stem-cell-therapy',
//   'neurological-therapy',
//   'tip-plasty',
//   'almond-eye',
//   'face-lift',
//   'bichecktomy',
//   'mommy-makeover',
//   'breast-reduction',
//   'male-breast-reduction',
//   'vaginal-tightening',
//   'implant-treatment',
//   'fillings',
//   'routine-check-ups',
//   'dental-x-rays',
//   'tooth-extractions',
//   'wisdom-teeth-removal',
//   'jaw-surgery',
//   'cataract-treatment',
//   'retinal-disease-treatment',
//   'lasik-surgery',
//   'smart-lens',
//   'ivf',
//   'fet-frozen-embryo-transfer'
