export const handleBFRelation = () => {
  const bfRelations = [
    {
      driveFolder: "THIGH LIFT",
      sizeNameFolder: "500_400",
      path: "thigh-lift",
      images: [
        "Before After 945.png",
        "Before After 944.png",
        "Before After 939.png",
        "Before After 938.png",
        "Before After 937.png",
        "Before After 936.png",
        "Before After 931.png",
        "Before After 929.png",
        "Before After 927.png",
        "Before After 925.png",
        "Before After 910.png",
        "Before After 909.png",
        "Before After 905.png",
        "Before After 903.png",
        "Before After 901.png",
      ],
    },
    {
      driveFolder: "RHINOPLASTY",
      sizeNameFolder: "500_400",
      path: "rhinoplasty-nose-reshaping",
      images: [
        "Копия Before After 190.png",
        "Копия Before After 188.png",
        "Копия Before After 181.png",
        "Before After 371.png",
        "Before After 320.png",
        "Before After 319.png",
        "Before After 318.png",
        "Before After 317.png",
        "Before After 316.png",
        "Before After 315.png",
        "Before After 314.png",
        "Before After 313.png",
        "Before After 312.png",
        "Before After 311.png",
        "Before After 310.png",
        "Before After 308.png",
        "Before After 307.png",
        "Before After 306.png",
        "Before After 305.png",
        "Before After 304.png",
        "Before After 303.png",
        "Before After 302.png",
        "Before After 301.png",
        "Before After 300.png",
        "Before After 299.png",
        "Before After 298.png",
        "Before After 254.png",
        "Before After 253.png",
        "Before After 252.png",
        "Before After 247.png",
        "Before After 246.png",
        "Before After 245.png",
        "Before After 244.png",
        "Before After 243.png",
        "Before After 242.png",
        "Before After 235.png",
        "Before After 234.png",
        "Before After 233.png",
        "Before After 229.png",
        "Before After 227.png",
        "Before After 225.png",
      ],
    },
    {
      driveFolder: "OTOPLASTY",
      sizeNameFolder: "500_400",
      path: "otoplasty",
      images: [
        "Before After 476.png",
        "Before After 474.png",
        "Before After 472.png",
        "Before After 470.png",
        "Before After 468.png",
        "Before After 464.png",
        "Before After 463.png",
        "Before After 461.png",
        "Before After 459.png",
        "Before After 458.png",
        "Before After 451.png",
        "Before After 449.png",
        "Before After 447.png",
      ],
    },
    {
      driveFolder: "MOMMY MAKEOVER",
      sizeNameFolder: "500_400",
      path: "mommy-makeover",
      images: [
        "Before After 778.png",
        "Before After 776.png",
        "Before After 774.png",
        "Before After 772.png",
        "Before After 761.png",
        "Before After 760.png",
        "Before After 759.png",
        "Before After 758.png",
        "Before After 757.png",
        "Before After 751.png",
        "Before After 749.png",
        "Before After 747.png",
        "Before After 744.png",
        "Before After 741.png",
      ],
    },
    {
      driveFolder: "LIPOSUCTION",
      sizeNameFolder: "500_400",
      path: "liposuction",
      images: [
        "Before After 750.png",
        "Before After 748.png",
        "Before After 746.png",
        "Before After 745.png",
        "Before After 743.png",
        "Before After 742.png",
        "Before After 740.png",
        "Before After 739.png",
        "Before After 725.png",
        "Before After 724.png",
        "Before After 723.png",
        "Before After 722.png",
        "Before After 721.png",
        "Before After 720.png",
        "Before After 718.png",
        "Before After 709.png",
        "Before After 708.png",
        "Before After 707.png",
        "Before After 706.png",
        "Before After 701.png",
        "Before After 699.png",
        "Before After 697.png",
        "Before After 695.png",
        "Before After 691.png",
        "Before After 689.png",
        "Before After 687.png",
      ],
    },
    {
      driveFolder: "FACELIFT",
      sizeNameFolder: "500_400",
      path: "face-lift",
      images: [
        "Before After 631.png",
        "Before After 629.png",
        "Before After 627.png",
        "Before After 625.png",
        "Before After 624.png",
        "Before After 623.png",
        "Before After 622.png",
        "Before After 621.png",
        "Before After 620.png",
        "Before After 619.png",
        "Before After 618.png",
        "Before After 617.png",
        "Before After 616.png",
        "Before After 615.png",
        "Before After 614.png",
        "Before After 601.png",
        "Before After 600.png",
        "Before After 599.png",
        "Before After 598.png",
        "Before After 597.png",
        "Before After 596.png",
        "Before After 589.png",
        "Before After 587.png",
        "Before After 583.png",
        "Before After 581.png",
        "Before After 579.png",
        "Before After 517.png",
        "Before After 516.png",
        "Before After 515.png",
        "Before After 514.png",
        "Before After 509.png",
        "Before After 508.png",
        "Before After 507.png",
        "Before After 506.png",
        "Before After 505.png",
        "Before After 504.png",
        "Before After 503.png",
        "Before After 502.png",
        "Before After 493.png",
        "Before After 492.png",
        "Before After 491.png",
        "Before After 490.png",
        "Before After 485.png",
        "Before After 484.png",
        "Before After 481.png",
        "Before After 479.png",
      ],
    },
    {
      driveFolder: "DOUBLE CHIN LIPOSUCTION",
      sizeNameFolder: "500_400",
      path: "double-chin-liposuction",
      images: [
        "Before After 577.png",
        "Before After 575.png",
        "Before After 573.png",
        "Before After 571.png",
        "Before After 569.png",
        "Before After 567.png",
        "Before After 565.png",
        "Before After 563.png",
        "Before After 561.png",
        "Before After 559.png",
        "Before After 557.png",
      ],
    },
    // {
    //   driveFolder: "BUTTOCK AUGMENTATION",
    //   sizeNameFolder: "500_400",
    //   path: "breast-augmentation-implants",
    //   images: [
    //     "Before After 1002.png",
    //     "Before After 1001.png",
    //     "Before After 1000.png",
    //     "Before After 995.png",
    //     "Before After 994.png",
    //     "Before After 990.png",
    //     "Before After 983.png",
    //     "Before After 982.png",
    //     "Before After 981.png",
    //     "Before After 980.png",
    //     "Before After 975.png",
    //     "Before After 974.png",
    //     "Before After 973.png",
    //     "Before After 969.png",
    //     "Before After 968.png",
    //     "Before After 967.png",
    //     "Before After 966.png",
    //     "Before After 961.png",
    //     "Before After 960.png",
    //     "Before After 959.png",
    //     "Before After 958.png",
    //     "Before After 957.png",
    //     "Before After 956.png",
    //     "Before After 955.png",
    //     "Before After 947.png",
    //     "Before After 946.png",
    //     "Before After 923.png",
    //     "Before After 922.png",
    //     "Before After 921.png",
    //     "Before After 920.png",
    //     "Before After 919.png",
    //     "Before After 918.png",
    //     "Before After 911.png",
    //   ],
    // },
    {
      driveFolder: "BREAST AUGMENTATION",
      sizeNameFolder: "500_400",
      path: "breast-augmentation-implants",
      images: [
        "Копия Before After 203.png",
        "Копия Before After 202.png",
        "Копия Before After 201.png",
        "Копия Before After 200.png",
        "Копия Before After 198.png",
        "Копия Before After 197.png",
        "Копия Before After 196.png",
        "Копия Before After 195.png",
        "Копия Before After 194.png",
        "Копия Before After 193.png",
        "Копия Before After 192.png",
        "Before After 1081.png",
        "Before After 1079.png",
        "Before After 1077.png",
        "Before After 1076.png",
        "Before After 1075.png",
        "Before After 1074.png",
        "Before After 1069.png",
        "Before After 1068.png",
        "Before After 1065.png",
        "Before After 1064.png",
        "Before After 1063.png",
        "Before After 1062.png",
        "Before After 1061.png",
        "Before After 1055.png",
        "Before After 1054.png",
        "Before After 1053.png",
        "Before After 1052.png",
        "Before After 1047.png",
        "Before After 1046.png",
        "Before After 1043.png",
        "Before After 1042.png",
        "Before After 1041.png",
        "Before After 1040.png",
        "Before After 1035.png",
        "Before After 1034.png",
        "Before After 1033.png",
        "Before After 1032.png",
        "Before After 1026.png",
        "Before After 1023.png",
        "Before After 1022.png",
        "Before After 1019.png",
        "Before After 1018.png",
        "Before After 1017.png",
        "Before After 1016.png",
        "Before After 1015.png",
        "Before After 1014.png",
        "Before After 1013.png",
        "Before After 1012.png",
        "Before After 1003.png",
      ],
    },
    {
      driveFolder: "BRAZILIAN BUTT LIFT",
      sizeNameFolder: "500_400",
      path: "brazilian-butt-lift",
      images: [
        "Before After 829.png",
        "Before After 825.png",
        "Before After 823.png",
        "Before After 816.png",
        "Before After 814.png",
        "Before After 812.png",
        "Before After 810.png",
        "Before After 808.png",
        "Before After 806.png",
        "Before After 804.png",
        "Before After 802.png",
        "Before After 781.png",
        "Before After 780.png",
        "Before After 779.png",
        "Before After 777.png",
        "Before After 775.png",
        "Before After 773.png",
      ],
    },
    {
      driveFolder: "BLEPHAROPLASTY",
      sizeNameFolder: "500_400",
      path: "blepharoplasty-upper-lower",
      images: [
        "Before After 406.png",
        "Before After 401.png",
        "Before After 400.png",
        "Before After 399.png",
        "Before After 398.png",
        "Before After 395.png",
        "Before After 394.png",
        "Before After 392.png",
        "Before After 390.png",
        "Before After 388.png",
        "Before After 386.png",
        "Before After 381.png",
        "Before After 380.png",
        "Before After 377.png",
        "Before After 375.png",
        "Before After 373.png",
        "Before After 368.png",
        "Before After 366.png",
        "Before After 364.png",
        "Before After 362.png",
        "Before After 360.png",
        "Before After 358.png",
      ],
    },
    {
      driveFolder: "ALMOND EYE AESTHETICS",
      sizeNameFolder: "500_400",
      path: "almond-eye",
      images: [
        "Before After 445.png",
        "Before After 437.png",
        "Before After 435.png",
        "Before After 427.png",
        "Before After 426.png",
        "Before After 425.png",
        "Before After 424.png",
        "Before After 423.png",
        "Before After 422.png",
        "Before After 418.png",
        "Before After 417.png",
        "Before After 416.png",
        "Before After 414.png",
        "Before After 412.png",
        "Before After 408.png",
      ],
    },
    {
      driveFolder: "TIPPLASTY",
      sizeNameFolder: "500_400",
      path: "tip-plasty",
      images: [
        "Before After 330.png",
        "Before After 332.png",
        "Before After 333.png",
        "Before After 334.png",
        "Before After 335.png",
        "Before After 336.png",
        "Before After 339.png",
        "Before After 340.png",
        "Before After 341.png",
        "Before After 342.png",
        "Before After 347.png",
        "Before After 348.png",
        "Before After 349.png",
        "Before After 350.png",
        "Before After 355.png",
        "Before After 519.png",
        "Before After 521.png",
        "Before After 523.png",
        "Before After 525.png",
        "Before After 527.png",
        "Before After 529.png",
        "Before After 531.png",
        "Before After 533.png",
        "Before After 535.png",
        "Before After 537.png",
        "Before After 539.png",
        "Before After 541.png",
        "Before After 543.png",
        "Before After 545.png",
        "Before After 547.png",
        "Before After 549.png",
        "Before After 551.png",
        "Before After 553.png",
        "Before After 555.png",
      ],
    },
    // new before after 2
    {
      isVersion2: true,
      driveFolder: "TUMMY TUCK",
      sizeNameFolder: "500_400",
      path: "tummy-tuck-abdominoplasty",
      images: [
        "Копия Before After 191.png",
        "Копия Before After 189.png",
        "Before After 899.png",
        "Before After 898.png",
        "Before After 895.png",
        "Before After 894.png",
        "Before After 891.png",
        "Before After 890.png",
        "Before After 889.png",
        "Before After 885.png",
        "Before After 884.png",
        "Before After 883.png",
        "Before After 879.png",
        "Before After 878.png",
        "Before After 877.png",
        "Before After 873.png",
        "Before After 871.png",
        "Before After 869.png",
        "Before After 860.png",
        "Before After 858.png",
        "Before After 856.png",
        "Before After 854.png",
        "Before After 845.png",
        "Before After 844.png",
        "Before After 843.png",
        "Before After 842.png",
        "Before After 837.png",
        "Before After 836.png",
        "Before After 833.png",
      ],
    },
    {
      isVersion2: true,
      driveFolder: "MALE BREAST REDUCTION",
      sizeNameFolder: "500-400",
      path: "male-breast-reduction",
      images: [
        "Before After 1138.png",
        "Before After 1136.png",
        "Before After 1134.png",
        "Before After 1133.png",
        "Before After 1132.png",
        "Before After 1131.png",
        "Before After 1130.png",
        "Before After 1129.png",
        "Before After 1128.png",
        "Before After 1127.png",
        "Before After 1118.png",
        "Before After 1117.png",
        "Before After 1116.png",
        "Before After 1115.png",
        "Before After 1110.png",
        "Before After 1109.png",
        "Before After 1106.png",
        "Before After 1104.png",
      ],
    },
    {
      isVersion2: true,
      driveFolder: "BREAST REDUCTION",
      sizeNameFolder: "500-400",
      path: "breast-reduction",
      images: [
        "Before After 1309.png",
        "Before After 1307.png",
        "Before After 1302.png",
        "Before After 1301.png",
        "Before After 1296.png",
        "Before After 1295.png",
        "Before After 1294.png",
        "Before After 1290.png",
        "Before After 1289.png",
        "Before After 1288.png",
        "Before After 1287.png",
        "Before After 1286.png",
        "Before After 1285.png",
        "Before After 1284.png",
        "Before After 1283.png",
        "Before After 1274.png",
        "Before After 1273.png",
        "Before After 1272.png",
        "Before After 1271.png",
        "Before After 1266.png",
        "Before After 1265.png",
        "Before After 1262.png",
        "Before After 1260.png",
        "Before After 1220.png",
      ],
    },
    {
      isVersion2: true,
      driveFolder: "BREAST LIFT",
      sizeNameFolder: "500-400",
      path: "breast-lift-mastopexy",
      images: [
        "Before After 1218.png",
        "Before After 1215.png",
        "Before After 1213.png",
        "Before After 1208.png",
        "Before After 1207.png",
        "Before After 1206.png",
        "Before After 1205.png",
        "Before After 1200.png",
        "Before After 1199.png",
        "Before After 1196.png",
        "Before After 1195.png",
        "Before After 1192.png",
        "Before After 1190.png",
        "Before After 1188.png",
        "Before After 1187.png",
        "Before After 1186.png",
        "Before After 1185.png",
        "Before After 1184.png",
        "Before After 1183.png",
        "Before After 1182.png",
        "Before After 1180.png",
        "Before After 1170.png",
        "Before After 1169.png",
        "Before After 1168.png",
        "Before After 1167.png",
        "Before After 1166.png",
        "Before After 1165.png",
        "Before After 1164.png",
        "Before After 1163.png",
        "Before After 1154.png",
        "Before After 1153.png",
        "Before After 1152.png",
        "Before After 1151.png",
        "Before After 1146.png",
        "Before After 1145.png",
        "Before After 1142.png",
        "Before After 1140.png",
      ],
    },
    {
      isVersion2: true,
      driveFolder: "ARM LIFT",
      sizeNameFolder: "500-400",
      path: "arm-lift",
      images: [
        "Before After 1437.png",
        "Before After 1436.png",
        "Before After 1435.png",
        "Before After 1434.png",
        "Before After 1433.png",
        "Before After 1432.png",
        "Before After 1431.png",
        "Before After 1430.png",
        "Before After 1429.png",
        "Before After 1428.png",
        "Before After 1427.png",
        "Before After 1426.png",
        "Before After 1425.png",
        "Before After 1101.png",
        "Before After 1086.png",
      ],
    },
    {
      isVersion2: true,
      driveFolder: "all-on-6-4",
      sizeNameFolder: "",
      path: "6-4-dental-implants",
      images: [
        "Before After 1311.png",
        "Before After 1313.png",
        "Before After 1315.png",
        "Before After 1316.png",
        "Before After 1319.png",
        "Before After 1320.png",
        "Before After 1321.png",
        "Before After 1322.png",
        "Before After 1328.png",
        "Before After 1329.png",
        "Before After 1331.png",
        "Before After 1333.png",
        "Before After 1334.png",
        "Before After 1343.png",
        "Before After 1344.png",
        "Before After 1345.png",
        "Before After 1347.png",
        "Before After 1348.png",
        "Before After 1349.png",
        "Before After 1358.png",
        "Before After 1360.png",
        "Before After 1361.png",
        "Before After 1364.png",
        "Before After 1367.png",
        "Before After 1375.png",
        "Before After 1378.png",
        "Before After 1388.png",
        "Before After 1391.png",
        "Before After 1392.png",
      ],
    },
    // new before after 3
    {
      isVersion3: true,
      driveFolder: "Dental Crowns",
      sizeNameFolder: "",
      path: "dental-crowns",
      images: [
        "Before After 1371.png",
        "Before After 1380.png",
        "Before After 1401.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Hollywood Smile",
      sizeNameFolder: "",
      path: "hollywood-smile",
      images: [
        "Before After 101.png",
        "Before After 1324.png",
        "Before After 1326.png",
        "Before After 1357.png",
        "Before After 1376.png",
        "Before After 1385.png",
        "Before After 139.png",
        "Before After 1393.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "LAMINATE VENEERS",
      sizeNameFolder: "",
      path: "laminate-veneers",
      images: [
        "Before After 131.png",
        "Before After 1323.png",
        "Before After 1332.png",
        "Before After 1335.png",
        "Before After 1336.png",
        "Before After 1340.png",
        "Before After 1341.png",
        "Before After 1373.png",
        "Before After 1381.png",
        "Before After 1390.png",
        "Before After 1396.png",
        "Before After 1402.png",
        "Before After 1404.png",
        "Before After 1406.png",
        "Before After 141.png",
        "Before After 147.png",
        "Before After 148.png",
        "Before After 149.png",
        "Before After 183.png",
        "Before After 184.png",
        "Before After 187.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Neck Lift",
      sizeNameFolder: "",
      path: "neck-lift",
      images: [
        "WhatsApp Image 2025-05-02 at 13.47.34.jpeg",
        "WhatsApp Image 2025-05-02 at 13.47.35 (1).jpeg",
        "WhatsApp Image 2025-05-02 at 13.47.35 (3).jpeg",
        "WhatsApp Image 2025-05-02 at 13.47.35 (4).jpeg",
        "WhatsApp Image 2025-05-02 at 13.47.35.jpeg",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Orthodontics",
      sizeNameFolder: "",
      path: "clear-aligners-invisalign",
      images: [
        "Before After 1314.png",
        "Before After 1337.png",
        "Before After 1339.png",
        "Before After 1342.png",
        "Before After 1346.png",
        "Before After 1354.png",
        "Before After 1355.png",
        "Before After 1365.png",
        "Before After 1366.png",
        "Before After 1369.png",
        "Before After 1370.png",
        "Before After 1399.png",
        "Before After 1403.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Whitening",
      sizeNameFolder: "",
      path: "teeth-whitening",
      images: [
        "Before After 1312.png",
        "Before After 1384.png",
        "Before After 140.png",
        "Before After 1414.png",
        "Before After 1416.png",
        "Before After 29.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Hair Transplantation Fue-DHI",
      sizeNameFolder: "",
      path: "dhi-hair-transplant",
      images: [
        "Before After 100.png",
        "Before After 114.png",
        "Before After 115.png",
        "Before After 117.png",
        "Before After 118.png",
        "Before After 119.png",
        "Before After 120.png",
        "Before After 121.png",
        "Before After 122.png",
        "Before After 123.png",
        "Before After 125.png",
        "Before After 126.png",
        "Before After 127.png",
        "Before After 130.png",
        "Before After 134.png",
        "Before After 135.png",
        "Before After 136.png",
        "Before After 137.png",
        "Before After 138.png",
        "Before After 88.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "Hair Transplantation Fue-DHI",
      sizeNameFolder: "",
      path: "fue-hair-transplant",
      images: [
        "Before After 100.png",
        "Before After 114.png",
        "Before After 115.png",
        "Before After 117.png",
        "Before After 118.png",
        "Before After 119.png",
        "Before After 120.png",
        "Before After 121.png",
        "Before After 122.png",
        "Before After 123.png",
        "Before After 125.png",
        "Before After 126.png",
        "Before After 127.png",
        "Before After 130.png",
        "Before After 134.png",
        "Before After 135.png",
        "Before After 136.png",
        "Before After 137.png",
        "Before After 138.png",
        "Before After 88.png",
      ],
    },
    {
      isVersion3: true,
      driveFolder: "IMPLANTOLOGY",
      sizeNameFolder: "",
      path: "implant-treatment",
      images: [
        "Before After 1317.png",
        "Before After 1318.png",
        "Before After 1338.png",
        "Before After 1372.png",
        "Before After 1382.png",
        "Before After 1400.png",
        "Before After 1417.png",
        "Before After 1418.png",
      ],
    },
  ];

  return bfRelations;
};

// 'fue-hair-transplant',
// 'dhi-hair-transplant',
// 'prp-hair-treatment',
// 'mesotherapy-hair',
// 'beard-transplant',
// 'moustache-transplant',
// 'eyebrow-transplant',
// 'rhinoplasty-nose-reshaping',
// 'blepharoplasty-upper-lower',
// 'labiaplasty-in-turkey',
// 'double-chin-liposuction',
// 'otoplasty',
// 'thighplasty-in-turkey',
// 'brow-lift',
// 'neck-lift',
// 'brazilian-butt-lift',
// 'liposuction',
// 'arm-lift',
// 'thigh-lift',
// 'breast-augmentation-implants',
// 'breast-lift-mastopexy',
// 'labiaplasty-barbie-look',
// 'penile-enlargement-phalloplasty',
// '6-4-dental-implants',
// 'root-canal-therapy',
// 'laminate-veneers',
// 'dental-crowns',
// 'teeth-whitening',
// 'hollywood-smile',
// 'clear-aligners-invisalign',
// 'gum-grafting',
// 'laser-gum-treatments',
// 'bone-grafting',
// 'tummy-tuck-abdominoplasty',
// 'glaucoma-treatment',
// 'diabetic-retinopathy-treatment',
// 'intraocular-lens',
// 'corneal-transplantation',
// 'male-infertility',
// 'male-sexual-health-issues',
// 'peyronies-disease',
// 'erectile-dysfunction-ed',
// 'stem-cell-for-men',
// 'orthopedic-stem-cell-therapy',
// 'neurological-therapy',
// 'tip-plasty',
// 'almond-eye',
// 'face-lift',
// 'bichecktomy',
// 'mommy-makeover',
// 'breast-reduction',
// 'male-breast-reduction',
// 'vaginal-tightening',
// 'implant-treatment',
// 'fillings',
// 'routine-check-ups',
// 'dental-x-rays',
// 'tooth-extractions',
// 'wisdom-teeth-removal',
// 'jaw-surgery',
// 'cataract-treatment',
// 'retinal-disease-treatment',
// 'lasik-surgery',
// 'smart-lens',
// 'ivf',
// 'fet-frozen-embryo-transfer'
