export const countryCodes = [
  { label: "Afghanistan", key: "+93", id: 1 },
  { label: "Albania", key: "+355", id: 2 },
  { label: "Algeria", key: "+213", id: 3 },
  { label: "Andorra", key: "+376", id: 4 },
  { label: "Angola", key: "+244", id: 5 },
  { label: "Argentina", key: "+54", id: 6 },
  { label: "Armenia", key: "+374", id: 7 },
  { label: "Australia", key: "+61", id: 8 },
  { label: "Austria", key: "+43", id: 9 },
  { label: "Azerbaijan", key: "+994", id: 10 },
  { label: "Bahamas", key: "+1-242", id: 11 },
  { label: "Bahrain", key: "+973", id: 12 },
  { label: "Bangladesh", key: "+880", id: 13 },
  { label: "Barbados", key: "+1-246", id: 14 },
  { label: "Belarus", key: "+375", id: 15 },
  { label: "Belgium", key: "+32", id: 16 },
  { label: "Belize", key: "+501", id: 17 },
  { label: "Benin", key: "+229", id: 18 },
  { label: "Bhutan", key: "+975", id: 19 },
  { label: "Bolivia", key: "+591", id: 20 },
  { label: "Bosnia and Herzegovina", key: "+387", id: 21 },
  { label: "Botswana", key: "+267", id: 22 },
  { label: "Brazil", key: "+55", id: 23 },
  { label: "Brunei Darussalam", key: "+673", id: 24 },
  { label: "Bulgaria", key: "+359", id: 25 },
  { label: "Burkina Faso", key: "+226", id: 26 },
  { label: "Burundi", key: "+257", id: 27 },
  { label: "Cabo Verde", key: "+238", id: 28 },
  { label: "Cambodia", key: "+855", id: 29 },
  { label: "Cameroon", key: "+237", id: 30 },
  { label: "Canada", key: "+1", id: 31 },
  { label: "Central African Republic", key: "+236", id: 32 },
  { label: "Chad", key: "+235", id: 33 },
  { label: "Chile", key: "+56", id: 34 },
  { label: "China", key: "+86", id: 35 },
  { label: "Colombia", key: "+57", id: 36 },
  { label: "Comoros", key: "+269", id: 37 },
  { label: "Congo (Congo-Brazzaville)", key: "+242", id: 38 },
  { label: "Congo (Democratic Republic)", key: "+243", id: 39 },
  { label: "Costa Rica", key: "+506", id: 40 },
  { label: "Croatia", key: "+385", id: 41 },
  { label: "Cuba", key: "+53", id: 42 },
  { label: "Cyprus", key: "+357", id: 43 },
  { label: "Czechia (Czech Republic)", key: "+420", id: 44 },
  { label: "Denmark", key: "+45", id: 45 },
  { label: "Djibouti", key: "+253", id: 46 },
  { label: "Dominica", key: "+1-767", id: 47 },
  { label: "Dominican Republic", key: "+1-809", id: 48 },
  { label: "Ecuador", key: "+593", id: 49 },
  { label: "Egypt", key: "+20", id: 50 },
  { label: "El Salvador", key: "+503", id: 51 },
  { label: "Equatorial Guinea", key: "+240", id: 52 },
  { label: "Eritrea", key: "+291", id: 53 },
  { label: "Estonia", key: "+372", id: 54 },
  { label: "Eswatini", key: "+268", id: 55 },
  { label: "Ethiopia", key: "+251", id: 56 },
  { label: "Fiji", key: "+679", id: 57 },
  { label: "Finland", key: "+358", id: 58 },
  { label: "France", key: "+33", id: 59 },
  { label: "Gabon", key: "+241", id: 60 },
  { label: "Gambia", key: "+220", id: 61 },
  { label: "Georgia", key: "+995", id: 62 },
  { label: "Germany", key: "+49", id: 63 },
  { label: "Ghana", key: "+233", id: 64 },
  { label: "Greece", key: "+30", id: 65 },
  { label: "Grenada", key: "+1-473", id: 66 },
  { label: "Guatemala", key: "+502", id: 67 },
  { label: "Guinea", key: "+224", id: 68 },
  { label: "Guinea-Bissau", key: "+245", id: 69 },
  { label: "Guyana", key: "+592", id: 70 },
  { label: "Haiti", key: "+509", id: 71 },
  { label: "Honduras", key: "+504", id: 72 },
  { label: "Hungary", key: "+36", id: 73 },
  { label: "Iceland", key: "+354", id: 74 },
  { label: "India", key: "+91", id: 75 },
  { label: "Indonesia", key: "+62", id: 76 },
  { label: "Iran", key: "+98", id: 77 },
  { label: "Iraq", key: "+964", id: 78 },
  { label: "Ireland", key: "+353", id: 79 },
  { label: "Israel", key: "+972", id: 80 },
  { label: "Italy", key: "+39", id: 81 },
  { label: "Jamaica", key: "+1-876", id: 82 },
  { label: "Japan", key: "+81", id: 83 },
  { label: "Jordan", key: "+962", id: 84 },
  { label: "Kazakhstan", key: "+7", id: 85 },
  { label: "Kenya", key: "+254", id: 86 },
  { label: "Kiribati", key: "+686", id: 87 },
  { label: "Korea (North)", key: "+850", id: 88 },
  { label: "Korea (South)", key: "+82", id: 89 },
  { label: "Kuwait", key: "+965", id: 90 },
  { label: "Kyrgyzstan", key: "+996", id: 91 },
  { label: "Laos", key: "+856", id: 92 },
  { label: "Latvia", key: "+371", id: 93 },
  { label: "Lebanon", key: "+961", id: 94 },
  { label: "Lesotho", key: "+266", id: 95 },
  { label: "Liberia", key: "+231", id: 96 },
  { label: "Libya", key: "+218", id: 97 },
  { label: "Liechtenstein", key: "+423", id: 98 },
  { label: "Lithuania", key: "+370", id: 99 },
  { label: "Luxembourg", key: "+352", id: 100 },
];
