export const options = [
  { isActive: true, label: "Dental", key: "dental-treatments", id: 0 },
  { isActive: false, label: "Ophthalmology and eye", key: "eye", id: 1 },
  { isActive: false, label: "Check-Ups", key: "aesthetic", id: 6 },
  { isActive: true, label: "Aesthetics", key: "aesthetic", id: 5 },
  { isActive: false, label: "Cardiology", key: "aesthetic", id: 7 },
  { isActive: false, label: "Stem Cell Transplants", key: "aesthetic", id: 8 },
  { isActive: true, label: "Stem Cell", key: "stem-cell", id: 3 },
  {
    isActive: false,
    label: "Neurology & Neurosurgery",
    key: "aesthetic",
    id: 9,
  },
  { isActive: false, label: "Orthopedics", key: "aesthetic", id: 10 },
  { isActive: true, label: "Fertility", key: "fertility", id: 4 },
  {
    isActive: false,
    label: "Bariatric (Weight Loss) Surgery",
    key: "aesthetic",
    id: 11,
  },
  {
    isActive: false,
    label: "Dermatology and Skin Treatments",
    key: "aesthetic",
    id: 12,
  },
  {
    isActive: true,
    label: "Ophthalmology and Eye Surgery",
    key: "eye-surgery",
    id: 17,
  },
  {
    isActive: false,
    label: "General & Laparoscopic Surgery",
    key: "aesthetic",
    id: 13,
  },
  { isActive: false, label: "Nephrology & Urology", key: "aesthetic", id: 14 },
  { isActive: false, label: "Spine Surgeries", key: "aesthetic", id: 15 },
  { isActive: false, label: "Organ Transplants", key: "aesthetic", id: 16 },
  {
    isActive: false,
    label: "ENT (Ear, Nose, and Throat) Surgery",
    key: "aesthetic",
    id: 18,
  },
  {
    isActive: false,
    label: "Pediatrics and Pediatric Surgery",
    key: "aesthetic",
    id: 19,
  },
  { isActive: false, label: "Oncology", key: "aesthetic", id: 20 },
  { isActive: false, label: "Addiction Treatment", key: "aesthetic", id: 21 },
  { isActive: false, label: "Wellness", key: "aesthetic", id: 22 },
  {
    isActive: false,
    label: "Physical Therapy and Rehabilitation",
    key: "aesthetic",
    id: 23,
  },
];
