export const options = [
  { label: "Dental", key: "dental-treatments", id: 0 },
  { label: "Ophthalmology and eye", key: "eye", id: 1 },
  { label: "Stem Cell", key: "stemcell", id: 3 },
  { label: "Fertility", key: "fertility", id: 4 },
  { label: "Aesthetics", key: "aesthetic", id: 5 },

  { label: "Check-Ups", key: "aesthetic", id: 6 },
  { label: "Cardiology", key: "aesthetic", id: 7 },
  { label: "Stem Cell Transplants", key: "aesthetic", id: 8 },
  { label: "Neurology & Neurosurgery", key: "aesthetic", id: 9 },
  { label: "Orthopedics", key: "aesthetic", id: 10 },
  { label: "Bariatric (Weight Loss) Surgery", key: "aesthetic", id: 11 },
  { label: "Dermatology and Skin Treatments", key: "aesthetic", id: 12 },
  { label: "General & Laparoscopic Surgery", key: "aesthetic", id: 13 },
  { label: "Nephrology & Urology", key: "aesthetic", id: 14 },
  { label: "Spine Surgeries", key: "aesthetic", id: 15 },
  { label: "Organ Transplants", key: "aesthetic", id: 16 },
  { label: "Ophthalmology and Eye Surgery", key: "aesthetic", id: 17 },
  { label: "ENT (Ear, Nose, and Throat) Surgery", key: "aesthetic", id: 18 },
  { label: "Pediatrics and Pediatric Surgery", key: "aesthetic", id: 19 },
  { label: "Oncology", key: "aesthetic", id: 20 },
  { label: "Addiction Treatment", key: "aesthetic", id: 21 },
  { label: "Wellness", key: "aesthetic", id: 22 },
  { label: "Physical Therapy and Rehabilitation", key: "aesthetic", id: 23 },
];
